name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print path
        run: |
          pwd

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Use Prime Numbers
        run: /primes.sh -d prime-numbers

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version