name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: |
          cat > myfile.txt
          Hello world
          ^C

      - uses: actions/checkout@v2

      - name: Cache myfile
        id: cache-myfile
        uses: actions/cache@v2
        with:
          path: myfile.txt
          key: ${{ runner.os }}-myfile

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version