name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: test flow
        run: |
          java -version
          mysql --version

      - name: installed software
        run: apt list --installed

  run-java-commands:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version