name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ant
        run: |
          sudo apt install zip
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.1-bin.zip
          unzip -o -q apache-ant-1.9.1-bin.zip -d /usr/local
          sudo ln -s /usr/local/apache-ant-1.9.1/ /usr/local/ant
          sudo vi /etc/profile.d/ant.sh
          export ANT_HOME=/usr/local/ant
          export PATH=${ANT_HOME}/bin:${PATH}
          source /etc/profile
          ant -version

      - uses: actions/checkout@v2
      - name: Print path
        run: |
          pwd
          ls -a

      - name: Cache readme
        id: cache-readme
        uses: actions/cache@v2
        with:
          path: README.md
          key: ${{ runner.os }}-readme-1

      - name: Print readme file from cache
        run: echo "${{ steps.cache-readme.outputs.cache-hit}}"

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version