name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ant
        run: |
          sudo apt install zip
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.1-bin.zip
          unzip -o -q ~/work/kafkademo/kafkademo/apache-ant-1.9.1-bin.zip
          cd ~
          mkdir Tools
          cd Tools
          mkdir ant
          mv  ~/work/kafkademo/kafkademo/apache-ant-1.9.1/* ~/Tools/ant
          cd ~/Tools/ant
          ls -l
          echo "=== before == "
          ant -version
          echo "=== before end == "
          export ANT_HOME="~/Tools/ant"
          export PATH=${ANT_HOME}/bin:${PATH}
          source /etc/profile
          echo "=== after == "
          ant -version
          echo "=== after end == "

      - uses: actions/checkout@v2
      - name: Print path
        run: |
          pwd
          ls -a

      - name: Cache readme
        id: cache-readme
        uses: actions/cache@v2
        with:
          path: README.md
          key: ${{ runner.os }}-readme-1

      - name: Print readme file from cache
        run: echo "${{ steps.cache-readme.outputs.cache-hit}}"

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version