name: test workflow
on:
  push:
    branches:
      - master
#  pull_request:
#  schedule:
#    - cron: '0/2 * * * *'
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ant
        run: |
          sudo apt install zip
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.1-bin.zip
          unzip -o -q apache-ant-1.9.1-bin.zip
          mkdir -p ~/Tools/ant
          echo "=== before == "
          cat  /etc/profile
          echo "=== before == "
          echo "====pass===="
          export ANT_HOME="~/Tools/ant"
          export PATH=${ANT_HOME}/bin:${PATH}
          source /etc/profile
          echo "=== after == "
          ant -version
          echo "=== after end == "


      - name: SonarCloud Scan
        id: sonar-scan
        if: ${{ needs.set-up.outputs.runSonarAnalysis == 'true' && matrix.plan == 'sonar' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=kafkademo
            -Dsonar.projectKey=kafkademo

      - uses: actions/checkout@v2
      - name: Print path
        run: |
          pwd
          ls -a

      - name: Cache readme
        id: cache-readme
        uses: actions/cache@v2
        with:
          path: README.md
          key: ${{ runner.os }}-readme-1

      - name: Print readme file from cache
        run: echo "${{ steps.cache-readme.outputs.cache-hit}}"

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version