name: test workflow
on: [push, pull_request]
jobs:
  my-test-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache readme
        id: cache-readme
        uses: actions/cache@v2
        run: |
          pwd
          ls -a
        with:
          path: README.md
          key: ${{ runner.os }}-readme

      - name: Print readme file from cache
        run: echo "${{ steps.cache-readme.outputs.cache-hit}}"

  print-cached-file:
    runs-on: ubuntu-latest
    steps:
      - name: print java version
        run: java -version